name: Build and deploy JAR app to Azure Web App - acme-salary

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "microsoft"
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package --file backend/pom.xml

      - name: Verify JAR exists
        shell: powershell
        run: |
          Get-ChildItem ".\backend\target\*.jar" |
            Where-Object { $_.Name -notlike "*.original" } |
            Format-Table FullName, Length

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E74CF9324DE1456D8A3525292007A58A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7BADF521A0944276925654D163A3EA4C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AFBD949EC724474B8F983865E6AC19C3 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "acme-salary"
          slot-name: "Production"
          package: "backend/target/*.jar"
